/* ************************************************************************** */
/*                                                                            */
/*                                                          :::      :::::::: */
/*   help_commands.rs                                     :+:      :+:    :+: */
/*                                                        +:+ +:+         +:+ */
/*   By: dlesieur <dev.pro.photo@gmail.com>                +#+  +:+       +#+ */
/*                                                          +#+#+#+#+#+   +#+ */
/*   Created: 2026/06/19 00:00:00 by dlesieur                      #+#    #+# */
/*   Updated: 2026/06/19 00:00:00 by dlesieur               ###   ########.fr */
/*                                                                            */
/* ************************************************************************** */

//! `42ctl help commands` — every runnable command with its arguments. Generated by walking the
//! clap tree rather than written by hand, so the reference is complete by construction: a verb
//! added under `cli/` appears here without anybody remembering to list it, and a flag renamed
//! there cannot survive here under its old name.

use crate::cli::Cli;
use crate::ui;
use clap::{Arg, ArgAction, Command, CommandFactory};

/// Column a synopsis wraps at, so the longest verbs stay readable in a narrow terminal.
const WIDTH: usize = 96;

/// Render the reference: a heading with the command count, the options every command takes,
/// then one section per command group in the order `--help` lists them.
pub fn page() -> String {
    let root = Cli::command();
    let globals: Vec<String> = root
        .get_arguments()
        .filter(|arg| arg.is_global_set())
        .map(token)
        .collect();
    let mut page = format!(
        "  {}  {}\n\n  Every command also takes {} and --help for its long form.\n",
        ui::title("42ctl help commands"),
        ui::dim(&format!(
            "— all {} commands, with their arguments",
            leaves(&root, &[]).len()
        )),
        globals.join(" ")
    );
    page.push_str(&sections(&root));
    page
}

/// Each top-level group as its own section; consecutive top-level verbs share one, titled by
/// their names, so `push · pull` read together instead of as two one-line sections.
fn sections(root: &Command) -> String {
    let mut out = String::new();
    let mut verbs: Vec<&Command> = Vec::new();
    for cmd in visible(root) {
        if cmd.has_subcommands() {
            out.push_str(&verb_section(&verbs));
            verbs.clear();
            out.push_str(&group_section(cmd));
        } else {
            verbs.push(cmd);
        }
    }
    out.push_str(&verb_section(&verbs));
    out
}

/// A section for a run of top-level verbs, or nothing for an empty run.
fn verb_section(verbs: &[&Command]) -> String {
    if verbs.is_empty() {
        return String::new();
    }
    let names: Vec<&str> = verbs.iter().map(|verb| verb.get_name()).collect();
    let mut out = ui::section(&names.join(" · "));
    for verb in verbs {
        out.push_str(&entry(&["42ctl", verb.get_name()], verb));
    }
    out
}

/// A section for one group: its summary, then every command beneath it at any depth.
fn group_section(group: &Command) -> String {
    let mut out = ui::section(group.get_name());
    out.push_str(&format!("  {}\n", ui::dim(&summary(group))));
    for (path, leaf) in leaves(group, &["42ctl"]) {
        out.push_str(&entry(&path, leaf));
    }
    out
}

/// Every runnable command at or under `cmd`, depth-first, each with its full path.
fn leaves<'a>(cmd: &'a Command, parent: &[&'a str]) -> Vec<(Vec<&'a str>, &'a Command)> {
    let mut path = parent.to_vec();
    path.push(cmd.get_name());
    if !cmd.has_subcommands() {
        return vec![(path, cmd)];
    }
    visible(cmd).flat_map(|sub| leaves(sub, &path)).collect()
}

/// The subcommands `--help` shows, in declaration order.
fn visible(cmd: &Command) -> impl Iterator<Item = &Command> {
    cmd.get_subcommands().filter(|sub| !sub.is_hide_set())
}

/// One command: its synopsis (positionals first, then options), then its summary dimmed.
fn entry(path: &[&str], cmd: &Command) -> String {
    let args: Vec<String> = cmd
        .get_positionals()
        .chain(cmd.get_arguments().filter(|arg| !arg.is_positional()))
        .filter(|arg| !arg.is_hide_set() && !arg.is_global_set())
        .map(token)
        .collect();
    let mut out = wrap(&path.join(" "), &args);
    out.push_str(&format!("        {}\n", ui::dim(&summary(cmd))));
    out
}

/// The first line of a command's doc, plus its visible aliases.
fn summary(cmd: &Command) -> String {
    let about = cmd.get_about().map(ToString::to_string).unwrap_or_default();
    let aliases: Vec<&str> = cmd.get_visible_aliases().collect();
    if aliases.is_empty() {
        return about;
    }
    format!("{about}  (alias: {})", aliases.join(", "))
}

/// One argument as a synopsis token: `<PATH>`, `--org <SLUG>`, `[--apply]`, `[PREFIX]`, and
/// `[--only <PATTERN>]...` for a repeatable one. Optional means "not required by the parser".
fn token(arg: &Arg) -> String {
    let value = arg
        .get_value_names()
        .and_then(|names| names.first())
        .map_or_else(|| arg.get_id().as_str().to_uppercase(), ToString::to_string);
    let bare = match arg.get_long() {
        Some(long) if arg.get_action().takes_values() => format!("--{long} <{value}>"),
        Some(long) => format!("--{long}"),
        None if arg.is_required_set() => format!("<{value}>"),
        None => value,
    };
    let shaped = if arg.is_required_set() {
        bare
    } else {
        format!("[{bare}]")
    };
    match arg.get_action() {
        ArgAction::Append => format!("{shaped}..."),
        _ => shaped,
    }
}

/// Lay `head` and its `args` out as one synopsis, wrapping under the first argument once a
/// line would pass `WIDTH`. Widths are counted on the plain text, before any styling.
fn wrap(head: &str, args: &[String]) -> String {
    let indent = 4 + head.chars().count() + 1;
    let mut out = format!("    {}", ui::bold(head));
    let mut column = indent - 1;
    for arg in args {
        if column + 1 + arg.chars().count() > WIDTH {
            out.push('\n');
            out.push_str(&" ".repeat(indent));
            column = indent;
        } else {
            out.push(' ');
            column += 1;
        }
        out.push_str(arg);
        column += arg.chars().count();
    }
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The page with any ANSI styling removed, so an assertion holds whether or not the test
    /// runner's stdout happens to be a terminal.
    fn plain(text: &str) -> String {
        let mut out = String::with_capacity(text.len());
        let mut in_escape = false;
        for ch in text.chars() {
            match (in_escape, ch) {
                (false, '\x1b') => in_escape = true,
                (false, _) => out.push(ch),
                (true, 'm') => in_escape = false,
                (true, _) => {}
            }
        }
        out
    }

    /// Every runnable command in the parser, as the space-joined path a user types.
    fn all_paths() -> Vec<String> {
        let root = Cli::command();
        leaves(&root, &[])
            .iter()
            .map(|(path, _)| path.join(" "))
            .collect()
    }

    /// The reference names every runnable command the parser knows. This is the property the
    /// page exists for, so it is measured against the parser rather than against a list.
    #[test]
    fn every_runnable_command_is_listed() {
        let page = plain(&page());
        for path in all_paths() {
            let listed =
                page.contains(&format!("    {path} ")) || page.contains(&format!("    {path}\n"));
            assert!(listed, "`{path}` is missing from `help commands`");
        }
    }

    /// Nested groups are walked to the bottom, and a group itself is not a runnable command.
    #[test]
    fn nested_groups_reach_their_leaves_and_groups_are_not_leaves() {
        let paths = all_paths();
        assert!(paths.contains(&"42ctl org github sync".to_string()));
        assert!(paths.contains(&"42ctl vault push-env".to_string()));
        assert!(!paths.contains(&"42ctl org github".to_string()));
        assert!(!paths.contains(&"42ctl vault".to_string()));
    }

    /// The synopsis says what the parser enforces: required flags bare, optional ones in
    /// brackets, repeatable ones marked, positionals by value name.
    #[test]
    fn a_synopsis_matches_what_the_parser_requires() {
        let page = plain(&page());
        assert!(page.contains("--org <SLUG>"));
        assert!(page.contains("[--apply]"));
        assert!(page.contains("[--only <PATTERN>]..."));
        assert!(page.contains("42ctl vault get <PATH> [--version <N>]"));
        assert!(page.contains("42ctl vault ls [PREFIX]"));
    }

    /// No synopsis line runs past the wrap column, however many flags a verb grows.
    #[test]
    fn no_synopsis_line_passes_the_wrap_column() {
        for line in plain(&page())
            .lines()
            .filter(|line| line.starts_with("    42ctl"))
        {
            assert!(line.chars().count() <= WIDTH, "too wide: {line}");
        }
    }
}
